server:
  port: 8081

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AjayKumarCS/config-service
          clone-on-start: true
          username: AjayKumarCS
          password: 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

